insert into problemas (id, link, nome)
values
-- entrada e saida
(1,'https://judge.beecrowd.com/pt/problems/view/1000','Hello World!'),
(2,'https://judge.beecrowd.com/pt/problems/view/1001','Extremamente Básico'),
(3,'https://judge.beecrowd.com/pt/problems/view/1002','Área do Círculo'),
(4,'https://judge.beecrowd.com/pt/problems/view/1003','Soma Simples'),
(5,'https://judge.beecrowd.com/pt/problems/view/1004','Produto Simples'),
(6,'https://judge.beecrowd.com/pt/problems/view/1005','Média 1'),
(7,'https://judge.beecrowd.com/pt/problems/view/1006','Média 2'),
(8,'https://judge.beecrowd.com/pt/problems/view/1007','Diferença'),
(9,'https://judge.beecrowd.com/pt/problems/view/1008','Salário'),
(10,'https://judge.beecrowd.com/pt/problems/view/1009','Salário com Bônus'),
(11,'https://judge.beecrowd.com/pt/problems/view/1014','Consumo'),
(12,'https://judge.beecrowd.com/pt/problems/view/1016','Distância'),
(13,'https://judge.beecrowd.com/pt/problems/view/1019','Conversão de Tempo'),
(14,'https://judge.beecrowd.com/pt/problems/view/1013','O Maior'),
(15,'https://judge.beecrowd.com/pt/problems/view/1012','Área'),
(16,'https://judge.beecrowd.com/pt/problems/view/1011','Esfera'),
(17,'https://judge.beecrowd.com/pt/problems/view/1010','Cálculo Simples'),
(18,'https://judge.beecrowd.com/pt/problems/view/1018','Cédulas'),
(19,'https://judge.beecrowd.com/pt/problems/view/1017','Gasto de Combustível'),
(20,'https://judge.beecrowd.com/pt/problems/view/1020','Idade em Dias'),

-- estruturas condicionais
(21,'https://judge.beecrowd.com/pt/problems/view/1035','Teste de Seleção 1'),
(22,'https://judge.beecrowd.com/pt/problems/view/1036','Fórmula de Bhaskara'),
(23,'https://judge.beecrowd.com/pt/problems/view/1037','Intervalo'),
(24,'https://judge.beecrowd.com/pt/problems/view/1038','Lanche'),
(25,'https://judge.beecrowd.com/pt/problems/view/1040','Média 3'),
(26,'https://judge.beecrowd.com/pt/problems/view/1041','Coordenadas de um Ponto'),
(27,'https://judge.beecrowd.com/pt/problems/view/1042','Sort Simples'),
(28,'https://judge.beecrowd.com/pt/problems/view/1043','Triângulo'),
(29,'https://judge.beecrowd.com/pt/problems/view/1044','Múltiplos'),
(30,'https://judge.beecrowd.com/pt/problems/view/1045','Tipos de Triângulos'),
(31,'https://judge.beecrowd.com/pt/problems/view/1046','Tempo de Jogo'),
(32,'https://judge.beecrowd.com/pt/problems/view/1047','Tempo de Jogo com Minutos'),
(33,'https://judge.beecrowd.com/pt/problems/view/1048','Aumento de Salário'),
(34,'https://judge.beecrowd.com/pt/problems/view/1049','Animal'),
(35,'https://judge.beecrowd.com/pt/problems/view/1050','DDD'),
(36,'https://judge.beecrowd.com/pt/problems/view/1051','Imposto de Renda'),
(37,'https://judge.beecrowd.com/pt/problems/view/1052','Mês'),
(38,'https://judge.beecrowd.com/pt/problems/view/1060','Números Positivos'),
(39,'https://judge.beecrowd.com/pt/problems/view/1061','Tempo de um Evento'),
(40,'https://judge.beecrowd.com/pt/problems/view/1064','Positivos e Média'),
(41,'https://judge.beecrowd.com/pt/problems/view/1065','Pares entre Cinco Números'),
(42,'https://judge.beecrowd.com/pt/problems/view/1066','Pares, Ímpares, Positivos e Negativos'),
(43,'https://judge.beecrowd.com/pt/problems/view/1067','Números Ímpares'),
(44,'https://judge.beecrowd.com/pt/problems/view/1070','Seis Números Ímpares'),
(45,'https://judge.beecrowd.com/pt/problems/view/1071','Soma de Impares Consecutivos I'),
(46,'https://judge.beecrowd.com/pt/problems/view/1072','Intervalo 2'),

-- laços de repetição
(47,'https://judge.beecrowd.com/pt/problems/view/1064','Positivos e Média'),
(48,'https://judge.beecrowd.com/pt/problems/view/1065','Pares entre Cinco Números'),
(49,'https://judge.beecrowd.com/pt/problems/view/1066','Pares, Ímpares, Positivos e Negativos'),
(50,'https://judge.beecrowd.com/pt/problems/view/1067','Números Ímpares'),
(51,'https://judge.beecrowd.com/pt/problems/view/1070','Seis Números Ímpares'),
(52,'https://judge.beecrowd.com/pt/problems/view/1071','Soma de Impares Consecutivos I'),
(53,'https://judge.beecrowd.com/pt/problems/view/1094','Experiências'),
(54,'https://judge.beecrowd.com/pt/problems/view/1101','Sequência de Números e Soma'),
(55,'https://judge.beecrowd.com/pt/problems/view/1080','Maior e Posição'),
(56,'https://judge.beecrowd.com/pt/problems/view/1095','Sequencia IJ 1'),
(57,'https://judge.beecrowd.com/pt/problems/view/1096','Sequencia IJ 2'),
(58,'https://judge.beecrowd.com/pt/problems/view/1097','Sequencia IJ 3'),
(59,'https://judge.beecrowd.com/pt/problems/view/1098','Sequencia IJ 4'),
(60,'https://judge.beecrowd.com/pt/problems/view/1099','Soma de Ímpares Consecutivos II'),
(61,'https://judge.beecrowd.com/pt/problems/view/1114','Senha Fixa'),
(62,'https://judge.beecrowd.com/pt/problems/view/1115','Quadrante'),
(63,'https://judge.beecrowd.com/pt/problems/view/1142','PUM'),
(64,'https://judge.beecrowd.com/pt/problems/view/1144','Sequência Lógica'),
(65,'https://judge.beecrowd.com/pt/problems/view/1145','Sequência Lógica 2'),
(66,'https://judge.beecrowd.com/pt/problems/view/1149','Somando Inteiros Consecutivos'),
(67,'https://judge.beecrowd.com/pt/problems/view/1150','Ultrapassando Z'),
(68,'https://judge.beecrowd.com/pt/problems/view/1059','Números Pares'),
(69,'https://judge.beecrowd.com/pt/problems/view/1159','Soma de Pares Consecutivos'),
(70,'https://judge.beecrowd.com/pt/problems/view/1060','Números Positivos'),
(71,'https://judge.beecrowd.com/pt/problems/view/1072','Intervalo 2'),
(72,'https://judge.beecrowd.com/pt/problems/view/1073','Quadrado de Pares'),
(73,'https://judge.beecrowd.com/pt/problems/view/1074','Par ou Ímpar'),
(74,'https://judge.beecrowd.com/pt/problems/view/1075','Resto 2'),
(75,'https://judge.beecrowd.com/pt/problems/view/1078','Tabuada'),
(76,'https://judge.beecrowd.com/pt/problems/view/1079','Médias Ponderadas'),

-- vetores e matrizes
(77,'https://judge.beecrowd.com/pt/problems/view/1172','Substituição em Vetor I'),
(78,'https://judge.beecrowd.com/pt/problems/view/1173','Preenchimento de Vetor I'),
(79,'https://judge.beecrowd.com/pt/problems/view/1174','Seleçao em Vetor I'),
(80,'https://judge.beecrowd.com/pt/problems/view/1175','Troca em Vetor I'),
(81,'https://judge.beecrowd.com/pt/problems/view/1176','Fibonacci em Vetor'),
(82,'https://judge.beecrowd.com/pt/problems/view/1177','Preenchimento de Vetor II'),
(83,'https://judge.beecrowd.com/pt/problems/view/1178','Preenchimento de Vetor III'),
(84,'https://judge.beecrowd.com/pt/problems/view/1179','Preenchimento de Vetor IV'),
(85,'https://judge.beecrowd.com/pt/problems/view/1180','Menor e Posição'),
(86,'https://judge.beecrowd.com/pt/problems/view/1181','Linha na Matriz'),
(87,'https://judge.beecrowd.com/pt/problems/view/1182','Coluna na Matriz'),
(88,'https://judge.beecrowd.com/pt/problems/view/1183','Acima da Diagonal Principal'),
(89,'https://judge.beecrowd.com/pt/problems/view/1184','Abaixo da Diagonal Principal'),
(90,'https://judge.beecrowd.com/pt/problems/view/1185','Acima da Diagonal Secundária'),
(91,'https://judge.beecrowd.com/pt/problems/view/1186','Abaixo da Diagonal Secundária'),
(92,'https://judge.beecrowd.com/pt/problems/view/1187','Área Superior'),
(93,'https://judge.beecrowd.com/pt/problems/view/1188','Área Inferior'),
(94,'https://judge.beecrowd.com/pt/problems/view/1189','Área Esquerda'),
(95,'https://judge.beecrowd.com/pt/problems/view/1190','Área Direita'),
(96,'https://judge.beecrowd.com/pt/problems/view/1557','Matriz Quadrada III'),
(97,'https://judge.beecrowd.com/pt/problems/view/2310','Voleibol'),
(98,'https://judge.beecrowd.com/pt/problems/view/2534','Exame Geral'),
(99,'https://judge.beecrowd.com/pt/problems/view/2542','Iu-Di-Oh!'),
(100,'https://judge.beecrowd.com/pt/problems/view/1435','Matriz Quadrada I'),
(101,'https://judge.beecrowd.com/pt/problems/view/1478','Matriz Quadrada II'),
(102,'https://judge.beecrowd.com/pt/problems/view/1534','Matriz 123'),
(103,'https://judge.beecrowd.com/pt/problems/view/1548','Fila do Recreio'),
(104,'https://judge.beecrowd.com/pt/problems/view/2552','PãodeQuejoSweeper'),
(105,'https://judge.beecrowd.com/pt/problems/view/1162','Organizador de Vagões'),
(106,'https://judge.beecrowd.com/pt/problems/view/2419','Costa'),

-- STL
(107,'https://judge.beecrowd.com/pt/problems/view/1022','TDA Racional'),
(108,'https://judge.beecrowd.com/pt/problems/view/1062','Trilhos'),
(109,'https://judge.beecrowd.com/pt/problems/view/1068','Balanço de Parênteses I'),
(110,'https://judge.beecrowd.com/pt/problems/view/1069','Diamantes e Areia'),
(111,'https://judge.beecrowd.com/pt/problems/view/1077','Infixa para Posfixa'),
(112,'https://judge.beecrowd.com/pt/problems/view/1110','Jogando Cartas Fora'),
(113,'https://judge.beecrowd.com/pt/problems/view/1211','Lista Telefônica Econômica'),
(114,'https://judge.beecrowd.com/pt/problems/view/1242','Ácido Ribonucleico Alienígena'),
(115,'https://judge.beecrowd.com/pt/problems/view/1261','Pontos de Feno'),
(116,'https://judge.beecrowd.com/pt/problems/view/1281','Ida à Feira'),
(117,'https://judge.beecrowd.com/pt/problems/view/1430','Composição de Jingles'),
(118,'https://judge.beecrowd.com/pt/problems/view/1520','Parafusos e Porcas'),
(119,'https://judge.beecrowd.com/pt/problems/view/1548','Fila do Recreio'),
(120,'https://judge.beecrowd.com/pt/problems/view/1608','Bolos da Maria'),
(121,'https://judge.beecrowd.com/pt/problems/view/1673','Codificação Run-length'),
(122,'https://judge.beecrowd.com/pt/problems/view/1763','Tradutor do Papai Noel'),
(123,'https://judge.beecrowd.com/pt/problems/view/2653','Dijkstra'),
(124,'https://judge.beecrowd.com/pt/problems/view/1944','BRINDE FACE 2015'),

-- strings
(125,'https://judge.beecrowd.com/pt/problems/view/2165','Tuitando'),
(126,'https://judge.beecrowd.com/pt/problems/view/1871','Zero vale Zero'),
(127,'https://judge.beecrowd.com/pt/problems/view/1803','Matring'),
(128,'https://judge.beecrowd.com/pt/problems/view/1607','Avance as Letras'),
(129,'https://judge.beecrowd.com/pt/problems/view/1061','Tempo de um Evento'),
(130,'https://judge.beecrowd.com/pt/problems/view/1581','Conversa Internacional'),
(131,'https://judge.beecrowd.com/pt/problems/view/1551','Frase Completa'),
(132,'https://judge.beecrowd.com/pt/problems/view/1516','Imagem'),
(133,'https://judge.beecrowd.com/pt/problems/view/1332','Um-Dois-Três'),
(134,'https://judge.beecrowd.com/pt/problems/view/1272','Mensagem Oculta'),
(135,'https://judge.beecrowd.com/pt/problems/view/1263','Aliteração'),
(136,'https://judge.beecrowd.com/pt/problems/view/1263','Aliteração'),
(137,'https://judge.beecrowd.com/pt/problems/view/1262','Leitura Múltipla'),
(138,'https://judge.beecrowd.com/pt/problems/view/1253','Cifra de César'),
(139,'https://judge.beecrowd.com/pt/problems/view/1241','Encaixa ou Não II'),
(140,'https://judge.beecrowd.com/pt/problems/view/1238','Combinador'),
(141,'https://judge.beecrowd.com/pt/problems/view/1024','Criptografia'),
(142,'https://judge.beecrowd.com/pt/problems/view/1234','Sentença Dançante'),
(143,'https://judge.beecrowd.com/pt/problems/view/1168','LED'),
(144,'https://judge.beecrowd.com/pt/problems/view/1873','Pedra-papel-tesoura-lagarto-Spock'),
(145,'https://judge.beecrowd.com/pt/problems/view/2242','Huaauhahhuahau'),
(146,'https://atcoder.jp/contests/agc006/tasks/agc006_a','Prefix and Suffix'),

-- matematica
(147,'https://codeforces.com/problemset/problem/1328/A','Divisibility Problem'),
(148,'https://atcoder.jp/contests/awc0002/tasks/awc0002_c','Observing Plant Growth'),
(149,'https://codeforces.com/contest/1352/problem/A','Sum of Round Numbers'),
(150,'https://atcoder.jp/contests/awc0001/tasks/awc0001_c','Discount Coupon'),
(151,'https://atcoder.jp/contests/abc391/tasks/abc391_c','Pigeonhole Query'),
(152,'https://codeforces.com/contest/1619/problem/B','Squares and Cubes'),
(153,'https://codeforces.com/contest/1272/problem/C','Yet Another Broken Keyboard'),

-- tecnicas basicas
(154,'https://codeforces.com/contest/1851/problem/B','Parity Sort'), -- two pointers
(155,'https://codeforces.com/contest/1213/problem/B','Bad Prices'), -- suffix minimum
(156,'https://cses.fi/problemset/task/1620','Factory Machines'), -- binary search
(157,'https://www.spoj.com/problems/ABACABA/en/','ABACABA - Print The Pattern'), -- divide and conquer
(158,'https://codeforces.com/group/c3FDl9EUi9/contest/262795/problem/H','Count a\''s'), -- suffix sum
(159,'https://cses.fi/problemset/task/1652','Forest Queries'), -- 2d suffix sum
(160,'https://onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=569','Passwords'), -- backtracking
(161,'https://atcoder.jp/contests/dp/tasks/dp_d','Knapsack 1'), -- dinamic programming

-- grafos
(162,'https://judge.beecrowd.com/pt/problems/view/1076','Desenhando Labirintos'),
(163,'https://judge.beecrowd.com/pt/problems/view/1082','Componentes Conexos'),
(164,'https://judge.beecrowd.com/pt/problems/view/1081','DFSr - Hierarquia de Profun…'),
(165,'https://judge.beecrowd.com/pt/problems/view/1100','Movimentos do Cavalo'),
(166,'https://judge.beecrowd.com/pt/problems/view/1317','Eu Odeio SPAM, Mas Algumas Pessoas Amam'),
(167,'https://judge.beecrowd.com/pt/problems/view/1469','Chefe'),
(168,'https://judge.beecrowd.com/pt/problems/view/1550','Inversão'),
(169,'https://judge.beecrowd.com/pt/problems/view/1610','Dudu Faz Serviço'),
(170,'https://judge.beecrowd.com/pt/problems/view/1773','Preso no Castelo'),
(171,'https://judge.beecrowd.com/pt/problems/view/1799','O Rato no Labirinto'),
(172,'https://judge.beecrowd.com/pt/problems/view/1835','Promessa de Campanha'),
(173,'https://judge.beecrowd.com/pt/problems/view/1855','Mapa do Meistre'),
(174,'https://judge.beecrowd.com/pt/problems/view/1907','Coloração de Cenários de Jogos'),
(175,'https://judge.beecrowd.com/pt/problems/view/1910','Ajude Clotilde'),
(176,'https://judge.beecrowd.com/pt/problems/view/1923','Rerisson e o Churrasco'),
(177,'https://judge.beecrowd.com/pt/problems/view/2562','Tipos Analógimôn'),
(178,'https://judge.beecrowd.com/pt/problems/view/1905','Polícia e Ladrão'),
(179,'https://judge.beecrowd.com/pt/problems/view/1862','Casas de Westeros'),
(180,'https://judge.beecrowd.com/pt/problems/view/3215','Dinheiro Importa'),
(181,'https://judge.beecrowd.com/pt/problems/view/2854','Árvore Genealógica'),
(182,'https://judge.beecrowd.com/pt/problems/view/2428','Capital'),
(183,'https://judge.beecrowd.com/pt/problems/view/1057','Chegando Junto'),
(184,'https://judge.beecrowd.com/pt/problems/view/1583','Contaminação'),
(185,'https://judge.beecrowd.com/pt/problems/view/1128','Ir e Vir'),
(186,'https://judge.beecrowd.com/pt/problems/view/1928','Jogo da Memória'),
(187,'https://judge.beecrowd.com/pt/problems/view/1669','Todos os Discos Considerados'),

-- grafos ponderados
(188,'https://judge.beecrowd.com/pt/problems/view/1123','Desvio de Rota'),
(189,'https://judge.beecrowd.com/pt/problems/view/1148','Países em Guerra'),
(190,'https://judge.beecrowd.com/pt/problems/view/1152','Estradas Escuras'),
(191,'https://judge.beecrowd.com/pt/problems/view/1205','Cerco a Leningrado'),
(192,'https://judge.beecrowd.com/pt/problems/view/1454','O País das Bicicletas'),
(193,'https://judge.beecrowd.com/pt/problems/view/1552','Resgate em Queda Livre'),
(194,'https://judge.beecrowd.com/pt/problems/view/1764','Itinerário do Papai Noel'),
(195,'https://judge.beecrowd.com/pt/problems/view/1774','Roteadores'),
(196,'https://judge.beecrowd.com/pt/problems/view/1806','Agente 004'),
(197,'https://judge.beecrowd.com/pt/problems/view/1972','Nêmesis'),
(198,'https://judge.beecrowd.com/pt/problems/view/1931','Mania de Par'),
(199,'https://judge.beecrowd.com/pt/problems/view/1977','Não Posso me Atrasar'),
(200,'https://judge.beecrowd.com/pt/problems/view/2683','Espaço de Projeto'),
(201,'https://judge.beecrowd.com/pt/problems/view/1956','Acácias'),
(202,'https://judge.beecrowd.com/pt/problems/view/1539','Empresa de Telecom'),
(203,'https://judge.beecrowd.com/pt/problems/view/2550','Novo Campus'),
(204,'https://judge.beecrowd.com/pt/problems/view/2566','Viagem Para BH'),
(205,'https://judge.beecrowd.com/pt/problems/view/1085','Babel'),
(206,'https://judge.beecrowd.com/pt/problems/view/1757','Viagem Barril'),
(207,'https://judge.beecrowd.com/pt/problems/view/3144','G de Grafo'),
(208,'https://judge.beecrowd.com/pt/problems/view/2528','Cidade Proibida'),
(209,'https://judge.beecrowd.com/pt/problems/view/2522','Rede do DINF'),

-- geometria computacional
(210,'https://judge.beecrowd.com/pt/problems/view/1039','Flores de Fogo'),
(211,'https://judge.beecrowd.com/pt/problems/view/1124','Elevador'),
(212,'https://judge.beecrowd.com/pt/problems/view/1223','Tobogan de Bolinhas'),
(213,'https://judge.beecrowd.com/pt/problems/view/1295','Problema dos Pares Mais Próximos'),
(214,'https://judge.beecrowd.com/pt/problems/view/1554','Bilhar N+1'),
(215,'https://judge.beecrowd.com/pt/problems/view/1296','Medianas'),
(216,'https://judge.beecrowd.com/pt/problems/view/1560','Energia dos Triângulos'),
(217,'https://judge.beecrowd.com/pt/problems/view/1631','O Fantástico Bolo de Bobby'),
(218,'https://judge.beecrowd.com/pt/problems/view/2203','Tempestade de Corvos'),
(219,'https://judge.beecrowd.com/pt/problems/view/1797','Ferozes e Curiosos'),
(220,'https://judge.beecrowd.com/pt/problems/view/1834','Vogons!'),
(221,'https://judge.beecrowd.com/pt/problems/view/1875','Tribol'),
(222,'https://judge.beecrowd.com/pt/problems/view/2158','Ajudando o Tio Cláudio'),
(223,'https://judge.beecrowd.com/pt/problems/view/1938','Praça do Retângulo'),
(224,'https://judge.beecrowd.com/pt/problems/view/1718','Pizza do Vô Pepe'),
(225,'https://judge.beecrowd.com/pt/problems/view/2878','Cortador de Pizza'),

-- tecnicas basicas
(226,'https://cses.fi/problemset/task/3220','Sliding Window Sum'),

-- Segment Tree
(227,'https://codeforces.com/edu/course/2/lesson/4/1/practice/contest/273169/problem/A','Segment Tree for the Sum'),
(228,'https://codeforces.com/edu/course/2/lesson/4/1/practice/contest/273169/problem/B','Segment Tree for the Minimum'),
(229,'https://codeforces.com/edu/course/2/lesson/4/1/practice/contest/273169/problem/C','Number of Minimums on a Segment'),

-- DFS
(230,'https://cses.fi/problemset/task/1666','Building Roads'),

-- Knapsack
(231,'https://cses.fi/problemset/task/1633','Dice Combinations'),
(232,'https://cses.fi/problemset/task/1635','Coin Combinations I'),

-- Binary Search
(233,'https://codeforces.com/edu/course/2/lesson/6/1/practice/contest/283911/problem/A','Binary Search'),
(234,'https://codeforces.com/edu/course/2/lesson/6/1/practice/contest/283911/problem/B','Closest to the Left'),
(235,'https://codeforces.com/edu/course/2/lesson/6/1/practice/contest/283911/problem/C','Closest to the Right'),

-- Segment Tree
(236,'https://codeforces.com/edu/course/2/lesson/4/3/practice/contest/274545/problem/A','Inversions'),
(237,'https://cses.fi/problemset/task/1144/','Salary Queries'),
(238,'https://codeforces.com/contest/61/problem/E','Enemy is weak'),
(239,'https://atcoder.jp/contests/abc343/tasks/abc343_f','Second Largest Query'),
(240,'https://www.spoj.com/problems/KQUERY/','KQUERY - K-query'),
(241,'https://codeforces.com/problemset/problem/1234/D','Distinct Characters Queries'),
(242,'https://codeforces.com/contest/380/problem/C','Sereja and Brackets'),
(243,'https://codeforces.com/contest/474/problem/F','Ant colony'),

-- Disjoint Set Union (DSU)
(244,'https://judge.yosupo.jp/problem/unionfind','Unionfind'),
(245,'https://cses.fi/problemset/task/1676','Road Construction'),
(246,'https://codeforces.com/edu/course/2/lesson/7/1/practice/contest/289390/problem/D','Cutting a graph'),
(247,'https://www.codechef.com/problems/ABROADS','Ancient Berland Roads'),
(248,'https://codeforces.com/edu/course/2/lesson/7/1/practice/contest/289390/problem/C','Experience'),

-- Ordered Set
(249,'https://www.spoj.com/problems/ORDERSET/en/','Order statistic set'),
(250,'https://www.spoj.com/problems/MEANARR/','Mean of Array'),
(251,'https://www.spoj.com/problems/KOILINE/','Line up'),
(252,'https://codeforces.com/contest/1042/problem/D','Petya and Array'),
(253,'https://www.spoj.com/problems/INVCNT/en/','Inversion Count'),
(254,'https://cses.fi/problemset/task/2163','Josephus Problem II'),

-- Trie
(255,'https://www.spoj.com/problems/ADAINDEX/','Ada and Indexing'),
(256,'https://www.spoj.com/problems/TRYCOMP/','Try to complete'),
(257,'https://atcoder.jp/contests/abc287/tasks/abc287_e','Karuta'),
(258,'https://www.codechef.com/problems/NPLFLF','Query on Strings'),
(259,'https://onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&page=show_problem&problem=3950','Shortest Names'),

-- Knapsack DP
(260,'https://cses.fi/problemset/task/1633','Dice Combinations'),
(261,'https://cses.fi/problemset/task/1635','Coin Combinations'),
(262,'https://atcoder.jp/contests/dp/tasks/dp_a','Frog 1'),
(263,'https://atcoder.jp/contests/dp/tasks/dp_b','Frog 2'),
(264,'https://cses.fi/problemset/task/1634','Minimizing Coins'),
(265,'https://cses.fi/problemset/task/1637','Removing Digits'),
(266,'https://codeforces.com/contest/687/problem/C','The Values You Can Make'),
(267,'https://cses.fi/problemset/task/1638','Grid Paths I'),
(268,'https://codeforces.com/contest/577/problem/B','Modulo Sum'),
(269,'https://cses.fi/problemset/task/1745','Money Sums'),
(270,'https://codeforces.com/gym/105925/problem/F','Feynman Memorizing Numbers'),

-- Digit Dp
(271,'https://cses.fi/problemset/task/2220','Counting Numbers'),
(272,'https://vjudge.net/problem/LightOJ-1068/origin','Investigation'),
(273,'https://atcoder.jp/contests/dp/tasks/dp_s','Digit Sum'),
(274,'https://codeforces.com/gym/100886/problem/G','Maximum Product'),
(275,'https://codeforces.com/contest/628/problem/D','Magic Numbers'),
(276,'https://lightoj.com/problem/digit-count','Digit Count'),
(277,'https://www.spoj.com/problems/CPCRC1C/','Sum of Digits'),
(278,'https://www.spoj.com/problems/RAONE/','Ra One Numbers'),
(279,'https://www.spoj.com/problems/LUCIFER/','Lucifer Numbers'),
(280,'https://codeforces.com/problemset/problem/204/A','Little Elephant and Interval'),

-- Bitmask Dp
(281,'https://atcoder.jp/contests/dp/tasks/dp_o','Matching'),
(282,'https://cses.fi/problemset/task/1690','Hamiltonian Flights'),
(283,'https://www.spoj.com/problems/PESADA04/en/','Travelling Salesman Problem'),
(284,'https://codeforces.com/contest/11/problem/D','A Simple Task'),
(285,'https://codeforces.com/contest/1316/problem/E','Team Building'),
(286,'https://usaco.org/index.php?page=viewproblem2&cpid=494','Guard Mark'),
(287,'https://usaco.org/index.php?page=viewproblem2&cpid=515','Moovie Mooving'),
(288,'https://codeforces.com/problemset/problem/8/C','Looking for Order'),
(289,'https://codeforces.com/contest/678/problem/E','Another Sith Tournament'),
(290,'https://cses.fi/problemset/task/1653','Elevator Rides'),

-- Sum Over Subset Dp
(291,'https://cses.fi/problemset/task/1654','SOS Bit Problem'),
(292,'https://codeforces.com/contest/165/problem/E','Compatible Numbers'),
(293,'https://codeforces.com/contest/383/problem/E','Vowels'),
(294,'https://cses.fi/problemset/task/3141/','And Subset Count'),
(295,'https://codeforces.com/contest/449/problem/D','Jzzhu and Numbers'),
(296,'https://atcoder.jp/contests/abc187/tasks/abc187_f','Close Group'),
(297,'https://www.hackerrank.com/contests/w16/challenges/vim-war/problem','Vim War'),
(298,'https://www.codechef.com/LTIME50/problems/MAXOR','Good Pairs'),
(299,'https://www.codechef.com/COOK126A/problems/ANDPREF','Prefix And'),
(300,'https://www.codechef.com/problems/MONSTER','Killing Monsters'),

-- Open and Close Trick
(301,'https://codeforces.com/contest/626/problem/F','Group Projects'),
(302,'https://cses.fi/problemset/task/1665','Coding Company'),
(303,'https://codeforces.com/contest/466/problem/D','Increase Sequence'),
(304,'https://codeforces.com/contest/367/problem/E','Sereja and Intervals'),
(305,'https://atcoder.jp/contests/abc452/tasks/abc452_d','No-Subsequence Substring'),

-- Longest Increasing Subsequence (LIS)
(306,'https://leetcode.com/problems/longest-increasing-subsequence/description/','Longest Increasing Subsequence (LIS)'),
(307,'https://cses.fi/problemset/task/1145','Increasing Subsequence'),
(308,'https://atcoder.jp/contests/dp/tasks/dp_q','Flowers'),
(309,'https://www.spoj.com/problems/DOSA/','Dosa'),
(310,'https://www.spoj.com/problems/HMLIS/','HowManyLis'),
(311,'https://www.spoj.com/problems/ONEXLIS/','One X LIS'),
(312,'https://atcoder.jp/contests/abc237/tasks/abc237_f','|LIS| = 3'),
(313,'https://www.spoj.com/problems/NDS/','Increasing Numbers'),
(314,'https://atcoder.jp/contests/arc091/tasks/arc091_c','LISDL'),
(315,'https://atcoder.jp/contests/abc165/tasks/abc165_f','LIS on Tree'),
(316,'https://codeforces.com/problemset/problem/486/E','LIS of Sequence'),

-- Interval Dp
(317,'https://vjudge.net/problem/Aizu-ALDS1_10_B','Matrix Chain Multiplication'),
(318,'https://www.spoj.com/problems/MIXTURES/','Mixtures'),
(319,'https://codeforces.com/contest/245/problem/H','Queries for Number of Palindromes'),
(320,'https://atcoder.jp/contests/dp/tasks/dp_n','Slimes'),
(321,'https://cses.fi/problemset/task/1080','Empty String'),
(322,'https://codeforces.com/problemset/problem/607/B','Zuma'),
(323,'https://codeforces.com/problemset/problem/607/B','Array Shrinking'),

-- Edit Distance
(324,'https://cses.fi/problemset/task/1639','Edit Distance'),
(325,'https://codeforces.com/gym/102001/problem/A','Edit Distance'),
(326,'https://codeforces.com/problemset/problem/530/G','Levenshtein distance'),
(327,'https://onlinejudge.org/index.php?option=onlinejudge&Itemid=8&page=show_problem&problem=4600','Back to Edit Distance'),
(328,'https://codeforces.com/problemset/problem/1282/D','Enchanted Artifact');
